# Generated by Django 4.2.4 on 2023-08-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app_books', '0002_alter_review_body_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='review',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ticket',
            name='content_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
