# Generated by Django 4.2.4 on 2023-08-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0003_review_content_type_review_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='review',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='object_id',
        ),
    ]
