# Generated by Django 4.2.4 on 2023-09-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0004_remove_review_content_type_remove_review_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='review_exist',
            field=models.BooleanField(default=False),
        ),
    ]
