# Generated by Django 4.2.4 on 2023-09-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0005_ticket_review_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='is_following',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
